stages:
   - check
   - Lint_Testing
   - approve
   - Unit_Testing


Check_master:
  stage:  check
  script:
    -  curl -sSfl https://raw.githubusercontent.com/omarabdalhamid/pipeline/master/check_master.sh |sh
  tags:
    - check
  only:
  - merge_requests

flake8:
  stage:  Lint_Testing
  script:
    -  curl -Ssfl https://raw.githubusercontent.com/omarabdalhamid/pipeline/master/flake8_test5.sh |sh
  tags:
    - lint_testing
  only:
  - merge_requests

OCA pylint_odoo:
  stage:  Lint_Testing
  script:
    -  curl -Ssfl https://raw.githubusercontent.com/omarabdalhamid/pipeline/master/pylint_odoo5.sh |sh
  tags:
    - lint_testing
  only:
  - merge_requests

approve:
  stage: approve
  script:
    - echo Hello!
  tags:
    - lint_testing  
  when: manual
  allow_failure: false 
  only:
  - merge_requests

Odoo_Unit_Testing:
   stage:  Unit_Testing
   script: 
#      -  curl -Ssfl  https://raw.githubusercontent.com/omarabdalhamid/pipeline/master/docker_test.sh |sh
       -  export COMPOSE_INTERACTIVE_NO_CLI=1
       -  docker exec -t e21e12a7c855 bash -c "odoo -d unit_test2 --db_host  db -w odoo --test-enable --test-tags  'standard,test_account_asset'"
   tags:
    - unit_test
  only:
  - merge_requests
