stages:
   - Check_Updates
   - Python_Lint_Testing
   - Odoo_Unit_Testing
   - Build_Application
   - SelenuimHQ
   - Cleaning
   - Code_Review
   - Deploy_Master_ENV
   - Deploy_Staging_ENV


Check_master:
  stage:  Check_Updates
  script:
    -  curl -sSfl https://raw.githubusercontent.com/omarabdalhamid/pipeline/master/check_master.sh |sh
  tags:
    - check
  only:
    - merge_requests

flake8:
  stage: Python_Lint_Testing
  script:
    -  curl -Ssfl https://raw.githubusercontent.com/omarabdalhamid/pipeline/master/flake8_test5.sh |sh
  tags:
    - lint_testing
  only:
    - merge_requests
    - master


OCA_pylint_odoo:
  stage:  Python_Lint_Testing
  script:
    -  curl -Ssfl https://raw.githubusercontent.com/omarabdalhamid/pipeline/master/pylint_odoo5.sh |sh
  tags:
    - lint_testing
  only:
    - merge_requests
    - master

approve:
  stage: Code_Review
  script:
    - echo " Project--> $CI_PROJECT_NAME \n  Branch_Name --> $CI_COMMIT_REF_NAME  \n Code has been Reviewed  and ready to merge into master" 
  tags:
    - check
  when: manual  
  only:
    - merge_requests

Odoo_Unit_Testing:
   stage:  Odoo_Unit_Testing
   script: 
       -  curl -Ssfl https://raw.githubusercontent.com/omarabdalhamid/pipeline/master/unit_test.sh |sh
   tags:
    - unit_test
   only:
    - merge_requests
    - master

Build_DB_postgres:
  stage: Build_Application
  script:
    - curl -Ssfl https://raw.githubusercontent.com/omarabdalhamid/pipeline/master/build_postgres.sh |sh  
  tags:
    - build
  only:
    - merge_requests
    - master

Build_Odoo_APP:
  stage: Build_Application
  script:
    - curl -Ssfl https://raw.githubusercontent.com/omarabdalhamid/pipeline/master/build_odoo.sh |sh 
  tags:
    - build
  only:
    - merge_requests
    - master

    
SeleniumHQ_E2E_Testing:
  stage: SelenuimHQ
  script:
    - curl -Ssfl https://raw.githubusercontent.com/omarabdalhamid/pipeline/master/e2e_testing.sh |sh
  tags:
    - build
  only:
    - merge_requests
    - master
    
Clean_Check_Stage:
  stage: Cleaning
  script:
    - echo "Stage Check Update has been cleaned"  
  tags:
    - check
  only:
    - merge_requests
    - master    

Clean_Lint_Stage:
  stage: Cleaning
  script:
    - echo "Stage Python_Lint_Testing has been cleaned"  
  tags:
    - check
  only:
    - merge_requests
    - master    

Clean_Unit_Stage:
  stage: Cleaning
  script:
    - echo "Stage Odoo_Unit_Testinghas been cleaned"  
  tags:
    - check
  only:
    - merge_requests
    - master    

Clean_Building_Application_Stage:
  stage: Cleaning
  script:
    - echo "Stage Building_Application has been cleaned"  
  tags:
    - check
  only:
    - merge_requests
    - master   
  

Clean_SelenuimHQ_Stage:
  stage: Cleaning
  script:
    - echo "Stage SelenuimHQ has been cleaned"  
  tags:
    - check
  only:
    - merge_requests
    - master   
 
Deploy_Master:
  stage: Deploy_Master_ENV
  script:
    - curl -Ssfl https://raw.githubusercontent.com/omarabdalhamid/pipeline/master/update_master.sh |sh
  environment:
    name: Master
    url: https://demo-project.master.itysys.net/
  tags:
    - staging
  only:
  - master
  
Deploy_Staging:
  stage: Deploy_Staging_ENV
  script:
    - curl -Ssfl https://raw.githubusercontent.com/omarabdalhamid/pipeline/master/update_staging.sh |sh
  environment:
    name: staging
    url: https://demo-project.staging.itysys.net/
  tags:
    - build
  when: manual  
  only:
  - master  
