stages:
    - deploy
    - Check_Updates

deploy_review:
  stage: deploy
  script:
    - sh /home/gitlab-runner/deploy-api.sh
  environment:
    name: API-zigames
    url: https://zigames-api.firmcom.net
  only:
    - master
    
deploy_review_basketball:
  stage: deploy
  script:
    - sh /home/gitlab-runner/deploy-basketball-api.sh
  environment:
    name: API-Basketball
    url: https://basketball-api.firmcom.net
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "basketball"'  
    
Check_master:
  stage:  Check_Updates
  script:
    -  sh /home/gitlab-runner/checkmaster.sh

  only:
    - merge_requests
    - branchs
