stages:
    - deploy
    - Check_Updates

deploy_review:
  stage: deploy
  script:
    - sh /home/gitlab-runner/deploy-api.sh
  environment:
    name: API-zigames
    url: https://zigames-api.firmcom.net
  only:
    - master
    
Check_master:
  stage:  Check_Updates
  script:
    -  sh /home/gitlab-runner/checkmaster.sh

  only:
    - merge_requests
    - branchs
