stages:
    - deploy
    - remove-review

deploy_review:
  stage: deploy
  script:
    - review-game
  environment:
    name: review/$CI_COMMIT_BRANCH
    url: https://review.zigames.firmcom.net/$CI_COMMIT_SHORT_SHA/
    on_stop: stop_review
  only:
    - branches
  except:
    - master 

stop_review:
  stage: deploy
  script:
    - stop-review
  when: manual
  environment:
    name: review/$CI_COMMIT_BRANCH
    action: stop
